apiVersion: batch/v1
kind: Job
metadata:
  name: kubescape-scan
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: kubescape-scan
        image: tray3rd/kubescape:test  # Replace with your built image
        command: [ "python3", "/entrypoint.py"]
        imagePullPolicy: Always
        volumeMounts:
        - name: repo-volume
          mountPath: /repos
        - name: output-volume
          mountPath: /output
      restartPolicy: Never
      volumes:
      - name: repo-volume
        emptyDir: {}
      - name: output-volume
        hostPath:
          path: /root/Jobs/kubescape-output
