apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-upload-job
spec:
  ttlSecondsAfterFinished: 30 # This will keep the job for 1 hour after completion
  template:
    spec:
      containers:
      - name: trivy-upload
        image: tray3rd/s3-upload:latest
        imagePullPolicy: Always
        env:
        - name: SEARCH_DIRECTORY
          value: "/trivy/output"
        - name: S3_BUCKET
          value: "sec-tooling-backend-tools-results-87238225"
        - name: S3_FOLDER
          value: "trivy"
        volumeMounts:
        - name: trivy-output
          mountPath: /trivy/output
      restartPolicy: Never
      volumes:
      - name: trivy-output
        hostPath:
          path: /root/Jobs/trivy-output  # Update this to your current directory path