apiVersion: batch/v1
kind: Job
metadata:
  name: checkov-append-job
spec:
  ttlSecondsAfterFinished: 30 
  template:
    spec:
      containers:
      - name: checkov-append
        image: python:3.8
        command: ["python", "/scripts/rename_json_files.py"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        - name: target-dir-volume
          mountPath: /target-dir
      restartPolicy: Never
            volumes:
      - name: script-volume
        configMap:
          name: trufflehog-append-script
          items:
          - key: modify_json_files.py
            path: modify_json_files.py
        name: checkov-append-script
      - name: target-dir-volume
        hostPath:
          path: "/root/Jobs/checkov-output"  # Replace with the actual path on your host
  backoffLimit: 4