apiVersion: batch/v1
kind: Job
metadata:
  name: checkov-scan
spec:
  ttlSecondsAfterFinished: 30 
  template:
    spec:
      containers:
      - name: checkov-scan
        image: tray3rd/checkov:test
        command: [ "python3", "run_checkov.py"]
        imagePullPolicy: Always
        volumeMounts:
        - name: repo-volume
          mountPath: /repos
        - name: output-volume
          mountPath: /output
      restartPolicy: Never
      volumes:
      - name: repo-volume
        emptyDir: {}
      - name: output-volume
        hostPath:
          path: /root/Jobs/checkov-output