apiVersion: batch/v1
kind: Job
metadata:
  name: zaproxy-append-job
spec:
  ttlSecondsAfterFinished: 30 
  template:
    spec:
      containers:
      - name: zaproxy-append
        image: python:3.9-alpine
        command: ["python3", "/scripts/modify_json_files.py"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: zaproxy-append-script
          items:
          - key: modify_json_files.py
            path: modify_json_files.py
      - name: data-volume
        hostPath:
          path: /root/Jobs/zaproxy-output  # Replace with your target directory
          type: Directory
