apiVersion: batch/v1
kind: Job
metadata:
  name: zaproxy-upload-job
spec:
  ttlSecondsAfterFinished: 30 # This will keep the job for 1 hour after completion
  template:
    spec:
      containers:
      - name: zaproxy-upload
        image: tray3rd/s3-upload:latest
        imagePullPolicy: Always
        env:
        - name: SEARCH_DIRECTORY
          value: "/zaproxy/output"
        - name: S3_BUCKET
          value: "sec-tooling-backend-tools-results-87238225"
        - name: S3_FOLDER
          value: "zaproxy"
        volumeMounts:
        - name: zaproxy-output
          mountPath: /zaproxy/output
      restartPolicy: Never
      volumes:
      - name: zaproxy-output
        hostPath:
          path: /root/Jobs/zaproxy-output  # Update this to your current directory path