apiVersion: v1
kind: ConfigMap
metadata:
  name: zaproxy-append-script
data:
  modify_json_files.py: |
    import os
    import json

    def add_site_owner(alerts, site_owner):
        for alert in alerts:
            alert["Site Owner"] = site_owner
            for instance in alert.get("instances", []):
                instance["Site Owner"] = site_owner

    def modify_json_files():
        # Get the current working directory
        current_dir = os.getcwd()

        # Walk through the directory tree
        for root, dirs, files in os.walk(current_dir):
            for file in files:
                if file.endswith('.json'):
                    # Get the full file path
                    file_path = os.path.join(root, file)

                    # Get the parent directory name
                    parent_dir = os.path.basename(root)

                    # Read the JSON content
                    with open(file_path, 'r') as json_file:
                        data = json.load(json_file)

                    # Modify the JSON content if the structure matches
                    if "site" in data:
                        for site in data["site"]:
                            site_owner = site.get("@name", parent_dir)
                            add_site_owner(site.get("alerts", []), site_owner)

                    # Write the updated JSON back to the file
                    with open(file_path, 'w') as json_file:
                        json.dump(data, json_file, indent=2)
                    print(f'Updated JSON content in {file_path}')

    if __name__ == "__main__":
        modify_json_files()
