apiVersion: batch/v1
kind: Job
metadata:
  name: zaproxy-scan
spec:
  ttlSecondsAfterFinished: 30 
  template:
    spec:
      containers:
      - name: zaproxy-scan
        image: tray3rd/zaproxy:test
        command: ["sh", "-c", "python3 /zap/run-zap.py"]
        imagePullPolicy: Always
        volumeMounts:
        - name: repo-volume
          mountPath: /zap/wrk
        - name: output-volume
          mountPath: /zap/output
      restartPolicy: Never
      volumes:
      - name: repo-volume
        emptyDir: {}
      - name: output-volume
        hostPath:
          path: /root/Jobs/zaproxy-output
