apiVersion: batch/v1
kind: Job
metadata:
  generateName: zaproxy-scan-s3-upload-job-
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: zaproxy-scan-s3-upload-container
        image: tray3rd/zaproxy-scan-s3-upload:latest
        env:
        - generateName: S3_BUCKET
          value: "tools-bucket-cloudranger-30293812"
        - generateName: S3_FOLDER
          value: "zaproxy"
        - generateName: AWS_DEFAULT_REGION
          value: "us-east-1"
        - generateName: SEARCH_DIRECTORY
          value: "/output"
        - generateName: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              generateName: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - generateName: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              generateName: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      restartPolicy: Never
  backoffLimit: 4
