apiVersion: batch/v1
kind: Job
metadata:
  name: prowler-job
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: prowler
        image: tray3rd/prowler:test
        command: ["prowler"]
        args: ["-M", "json-ocsf", "-S", "-q"]
        volumeMounts:
        - name: output-volume
          mountPath: /root/output  # Update mountPath to match root user
        securityContext:
          runAsUser: 0  # Root user
          runAsGroup: 0  # Root group
      restartPolicy: Never
      volumes:
      - name: output-volume
        hostPath:
          path: /root/Jobs/prowler-output  # Replace with your desired path
  backoffLimit: 4
