apiVersion: batch/v1
kind: Job
metadata:
  name: trufflehog-upload-job
spec:
  ttlSecondsAfterFinished: 30 # This will keep the job for 1 hour after completion
  template:
    spec:
      containers:
      - name: trufflehog-upload
        image: tray3rd/s3-upload:latest
        imagePullPolicy: Always
        env:
        - name: SEARCH_DIRECTORY
          value: "/trufflehog/output"
        - name: S3_BUCKET
          value: "sec-tooling-backend-tools-results-87238225"
        - name: S3_FOLDER
          value: "trufflehog"
        volumeMounts:
        - name: trufflehog-output
          mountPath: /trufflehog/output
      restartPolicy: Never
      volumes:
      - name: trufflehog-output
        hostPath:
          path: /root/Jobs/trufflehog-output  # Update this to your current directory path